apiVersion: v1
kind: PersistentVolume
metadata:
  name: jl-vke-nas-static-pv-sub
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: nas.csi.volcengine.com
    volumeAttributes:
      fsId: enas-xxxxxx
      fsType: Extreme
      path: /enas-xxxxxx # The subdirectory OR root of the NAS file system that you want to mount.
      server: xxxxx.nas.ibytepluses.com  # The mount target of the NAS file system.
      volumeAs: filesystem # change to subpath if you use subdirectory
    volumeHandle: jl-vke-nas-static-pv-sub
  mountOptions:
  - nolock,proto=tcp,noresvport
  - vers=3
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem