apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jl-vke-nas-static-pvc-sub
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: jl-vke-nas-static-pv-sub